### PR TITLE
Icon suggestion: copy to clipboard

### PR DESCRIPTION
**Pull request by AlencarGabriel**

### CODE REVIEW

**Comment by miguelsolorio** [comment]
@AlencarGabriel hey, thanks for the PR! But we actually already have a clipboard icon called `clippy`. Did you see this one? https://github.com/microsoft/vscode-icons/blob/main/icons/light/clippy.svg

**Comment by AlencarGabriel** [comment]
Hi @misolori,

this is actually a "copy to clipboard" icon:

image

**Comment by miguelsolorio** [comment]
That's also the same way we use the `clippy` icon 😄

**Comment by AlencarGabriel** [comment]
Got it. So okay, you can discard this PR.

Thanks for the clarification.

**Comment by miguelsolorio** [comment]
Sorry for the trouble!

**Pull request closed without merging**
