### PR TITLE
Add dark variant links to README

### PR DESCRIPTION
**Pull request by usernamehw**
It's not perfect because the background is not dark, but users can see how the dark icons look on the big image above.

These links though should allow to download both versions in the quickest way.

|    Before     |   After        |
| ------------- |-------------|
|Screenshot (82)  | Screenshot (83)  |

Also, centered the icons.

### CODE REVIEW

**Review by miguelsolorio — CHANGES_REQUESTED** [review]
Thanks for taking a look at this! I only recently added the icon previews, but I'm already worried that the README takes several seconds to load as it's making +300 requests for each image. Adding a dark variant will only make that worse, and even though it's not adding much value as it's not shown in the right context.

Instead, can you try to add a column that has links to each dark/light version? That would be much more helpful. Thanks!

**Comment by usernamehw** [comment]
> Instead, can you try to add a column that has links to each dark/light version?

Not sure I understand this correctly. Should it be like this?:

|    Name     |  Preview Light         | Link Dark
| ------------- |-------------|---|
|activate-breakpoints||[activate-breakpoints](https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/dark/activate-breakpoints.svg?sanitize=true)|

**Comment by miguelsolorio** [comment]
@usernamehw sorry, I meant more like:

|Name|Preview|Links|
|---|---|---|
|activate-breakpoints| |[Light](https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/activate-breakpoints.svg) - [Dark](https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/dark/activate-breakpoints.svg)|

**Comment by usernamehw** [comment]
Made some changes. It looks like this now:

| Name | Icon | Links |
| :--- | :---: | :---: |
activate-breakpoints||[Light](https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/activate-breakpoints.svg?sanitize=true) / [Dark](https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/dark/activate-breakpoints.svg?sanitize=true)|

Changed `Preview` column name to `Icon` for it to become smaller.

**Comment by waldyrious** [comment]
May I suggest taking this opportunity to place the full table in a file other than README (but linked from it)? As it is, not only it's slower to load, but also requires a lot of scrolling.

**Review by miguelsolorio — APPROVED** [review]
LGTM!

**Pull request merged**
